theme: jekyll-theme-slate
title: Benhur Gürel
author:
  name: Benhur Gürel
  email: guerel@tuta.io
description: >
  bguerel.github.io
show_downloads: false
google_analytics: UA-147142024-3
google_verify: CYwrcfCC0DN5gAKOI4JruNacFUJUkbNdXK8tZXbWyEg
github:
  repository_url: https://github.com/bguerel
 
# timezone: "Europe/Berlin"
# markdown: kramdown
  
# Social
social_links:
  github: bguerel
  twitter: b_guerel
  # facebook: jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # youtube: jekyll
  # youtube_channel: XXXX-XXXX
  # youtube_channel_name: jekyll
  # telegram: jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
